# Generated by Django 4.2.11 on 2024-03-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.IntegerField()),
                ('ProductName', models.CharField(max_length=200)),
                ('Description', models.TextField(max_length=500)),
                ('SupplierID', models.IntegerField()),
                ('CategoryID', models.IntegerField()),
                ('Unit', models.CharField(max_length=200)),
                ('Price', models.IntegerField(default=0)),
                ('Image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
