# Generated by Django 4.2.11 on 2024-03-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Buku', models.IntegerField()),
                ('Kategori', models.CharField(max_length=500)),
                ('Nama_Buku', models.CharField(max_length=200)),
                ('Harga', models.IntegerField()),
                ('Stok', models.IntegerField()),
                ('Penerbit', models.CharField(max_length=200)),
                ('Image', models.ImageField(default='', upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
