# Generated by Django 4.2.11 on 2024-03-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybookstore', '0002_buku_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='ID_Buku',
            field=models.CharField(max_length=5),
        ),
    ]
