# Generated by Django 4.2.11 on 2024-03-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybookstore', '0003_alter_buku_id_buku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penerbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Penerbit', models.CharField(max_length=5)),
                ('Nama', models.CharField(max_length=200)),
                ('Alamat', models.CharField(max_length=200)),
                ('Kota', models.CharField(max_length=200)),
                ('Telepon', models.CharField(max_length=200)),
                ('Image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
