# Generated by Django 4.2.11 on 2024-03-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCV', '0003_alter_berita_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='berita',
            old_name='image',
            new_name='pic',
        ),
    ]
