# Generated by Django 4.2.11 on 2024-03-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCV', '0004_rename_image_berita_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='description',
            field=models.TextField(max_length=900),
        ),
    ]
