# Generated by Django 4.2.11 on 2024-03-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCV', '0005_alter_berita_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rate',
        ),
        migrations.AddField(
            model_name='review',
            name='img',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
